name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  trigger_ci:
    uses: softwok/github-actions/.github/workflows/go-pkg-ci.yml@main
    with:
      service-name: common-util
    secrets: inherit